// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pftgnqacnrreujlvfwgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdGducWFjbnJyZXVqbHZmd2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzQyNTgsImV4cCI6MjA1NDExMDI1OH0.D2Sugar-Ua-ibFsjkgsbBffUS_xKWe-sk4o4OTi2PtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);